/*
###############################################################
#  Generated by:      Cadence Innovus 16.26-s040_1
#  OS:                Linux x86_64(Host ID raman1)
#  Generated on:      Sat Oct 16 20:21:13 2021
#  Design:            counter
#  Command:           saveNetlist counter.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 16 2021 18:11:27 IST (Oct 16 2021 12:41:27 UTC)
// Verification Directory fv/counter 
module counter (
	clk, 
	rst, 
	out);
   input clk;
   input rst;
   output [2:0] out;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;

   NR2M2R g196 (.A(n_5),
	.B(rst),
	.Z(n_6));
   AOI32M2R g198 (.A1(n_0),
	.A2(out[0]),
	.A3(out[1]),
	.B1(n_4),
	.B2(out[2]),
	.Z(n_5));
   DFQM2RA \out_reg[0]  (.CK(clk),
	.D(n_3),
	.Q(out[0]));
   AOI211M2R g200 (.A1(n_2),
	.A2(out[2]),
	.B(out[0]),
	.C(rst),
	.Z(n_3));
   MXB2M1RA g201 (.A(n_2),
	.B(out[1]),
	.S(out[0]),
	.Z(n_4));
   CKINVM2R g203 (.A(rst),
	.Z(n_1));
   DFZRM2RA \out_reg[1]  (.CK(clk),
	.D(n_1),
	.Q(out[1]),
	.QB(n_2),
	.RB(n_4));
   DFM2RA \out_reg[2]  (.CK(clk),
	.D(n_6),
	.Q(out[2]),
	.QB(n_0));
endmodule

